import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const navSource = readFileSync(new URL('../src/components/MobileBottomNav.tsx', import.meta.url), 'utf8');
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const feedSource = readFileSync(new URL('../src/pages/CommunityFeedPage.tsx', import.meta.url), 'utf8');
const editorSource = readFileSync(new URL('../src/pages/CommunityEditorPage.tsx', import.meta.url), 'utf8');
const postSource = readFileSync(new URL('../src/pages/CommunityPostPage.tsx', import.meta.url), 'utf8');
const commentsSource = readFileSync(new URL('../src/components/community/CommunityComments.tsx', import.meta.url), 'utf8');
const cardSource = readFileSync(new URL('../src/components/community/CommunityPostCard.tsx', import.meta.url), 'utf8');
const accountSource = readFileSync(new URL('../src/pages/MyAccountPage.tsx', import.meta.url), 'utf8');

assert.match(navSource, /'community'/);
assert.match(navSource, /MessageCircleMore/);
assert.match(navSource, /label: '广场'/);
assert.match(navSource, /grid-cols-5/);
assert.match(appSource, /CommunityFeedPage/);
assert.match(appSource, /publicView === 'community'/);
assert.match(feedSource, /推荐/);
assert.match(feedSource, /最新/);
assert.match(feedSource, /发布感想/);
assert.match(feedSource, /currentUser: AuthUser \| null/);
assert.match(feedSource, /onLoginClick: \(\) => void/);
assert.match(feedSource, /listPublished\(topic, currentUser\?\.userId\)/);
assert.match(feedSource, /toggleReaction\(currentUser\.userId, post\.id, 'like'\)/);
assert.match(feedSource, /setCommunityPostLike/);
assert.match(feedSource, /readCommunityFeedCache/);
assert.match(feedSource, /writeCommunityFeedCache/);
assert.match(feedSource, /const cached = readCommunityFeedCache\(topic, currentUser\?\.userId\)/);
assert.match(feedSource, /setLoading\(!cached\)/);
assert.match(feedSource, /writeCommunityFeedCache\(topic, currentUser\?\.userId, nextPosts\)/);
assert.match(appSource, /currentUser=\{currentUser\}/);
assert.match(appSource, /onLoginClick=\{\(\) => setShowAuth\(true\)\}/);
assert.match(editorSource, /maxLength=\{10_000\}/);
assert.match(editorSource, /存草稿/);
assert.match(editorSource, /草稿已保存/);
assert.match(editorSource, /确认封面/);
assert.match(appSource, /openCommunityEditorAfterLogin/);
assert.match(postSource, /toggleReaction/);
assert.match(cardSource, /onLike: \(post: CommunityPost\) => void/);
assert.match(cardSource, /aria-pressed=\{Boolean\(post\.likedByCurrentUser\)\}/);
assert.match(cardSource, /aria-label=\{post\.likedByCurrentUser \? '取消点赞' : '点赞'\}/);
assert.doesNotMatch(cardSource, /return \(\s*<button[\s\S]*className="w-full overflow-hidden/);
assert.match(postSource, /内容已删除或不存在/);
assert.match(commentsSource, /评论最多 1000 字/);
assert.match(commentsSource, /请先登录后评论/);
assert.match(accountSource, /listMine\(userId, 'published'\)/);
assert.match(accountSource, /listMine\(userId, 'draft'\)/);
assert.match(accountSource, /我的发布/);
assert.match(accountSource, /我的草稿/);

console.log('community navigation checks passed');
